### ISSUE TITLE
Possible to point URL at a cluster of servers?

### ISSUE THREAD

**Issue by ssenaria** [FriendsOfPHP/consul-php-sdk#15]
I have a cluster of 3 Consul servers. How can I have my code point at a random server instead of specifying only one server?

**Comment by lyrixx** [comment]
Actually, you can not with the lib. But you can easy create a wrapper to do so.

**Comment by delamart** [comment]
I think the correct way to do this would be to run a consul agent (not a server) on the localhost and the agent will take care of communicating with the cluster.

**Comment by lyrixx** [comment]
I agree. And this is how consul is supposed to be used. That's why I'm closing this issue.
