### ISSUE TITLE
Support txn

### ISSUE THREAD

**Issue by jasonrsmith** [FriendsOfPHP/consul-php-sdk#22]
Hi,

It'd be nice to add support to consul's txn api so we can atomically alter kv's with this library.

Thanks!
## 

Jason

**Comment by lyrixx** [comment]
Hello @jasonrsmith 

Could you open a PR?

---

For more information about [txn, see the doc](https://www.consul.io/docs/agent/http/kv.html#txn)

**Comment by andre-exads** [comment]
Hi there,

I didn't manage to open a PR, could you please check this @lyrixx ...

https://github.com/FriendsOfPHP/consul-php-sdk/compare/v4.0.0...andre-exads:master

**Comment by lyrixx** [comment]
@andre-exads I opened the PR for you :)

**Comment by lyrixx** [comment]
fixed via #54
