### ISSUE TITLE
X-Consul-Token in header to work with Consul ACL

### ISSUE THREAD

**Issue by Chintanvpatel** [FriendsOfPHP/consul-php-sdk#27]
Hello,

Currently, Is there any way to pass consul acl token in header ( X-Consul-Token ) ? I forked this repo & made some changes to pass token in query string.

[https://github.com/Chintanvpatel/consul-php-sdk/commit/de939942e7163848f9dfaed7cef488a66b8beb17](https://github.com/Chintanvpatel/consul-php-sdk/commit/de939942e7163848f9dfaed7cef488a66b8beb17)

Regards.

**Comment by sebastianreloaded** [comment]
hi,
you can just pass the header to the GuzzleClient via the ServiceFactory:
$sf = new SensioLabs\Consul\ServiceFactory(['headers' => ['X-Consul-Token' => 'some_uuid_token']]);

**Comment by lyrixx** [comment]
@Chintanvpatel You code looks good to me. Could you submit a PR to this repo ?
**Warning:** we moved the repository this morning

**Comment by lyrixx** [comment]
Closing for lake of activity
