### ISSUE TITLE
Bumping into PHP-7.1+ version supports

### ISSUE THREAD

**Issue by peter279k** [FriendsOfPHP/consul-php-sdk#41]
As title, the `php-5.6` and `php-7.0` versions have been inactive for about whiles.

And I think it's time to drop `php-5.6` and `php-7.0` versions now.

Once this issue is accepted, I can work on this :).

**Comment by lyrixx** [comment]
> Once this issue is accepted, I can work on this :).

Yes please :) 

Thanks a lot
