### ISSUE TITLE
$kv->get() returns empty string

### ISSUE THREAD

**Issue by scortellino** [FriendsOfPHP/consul-php-sdk#44]
Hi,

I'm doing the following call
```php
$kv = $sf->get(\SensioLabs\Consul\Services\KVInterface::class);
$env = $kv->get('environment/name', ['raw' => true])->getBody();
echo $env;
```
 
And I get an empty string. When i go to consul, the value is indeed there. 

I also deleted the key from Consul and called the "put" function just to see if the api does something...
```php
$kv = $sf->get(\SensioLabs\Consul\Services\KVInterface::class);
$kv->put('environment/name', 'dev');
$env = $kv->get('environment/name', ['raw' => true])->getBody();
echo $env;
```

And it was able to put the value when I refreshed the page.

![Screen Shot 2020-01-09 at 5 06 56 PM](https://user-images.githubusercontent.com/12703920/72108982-c7027680-3302-11ea-94a2-2e7daa88958e.png)

I'm not quite sure what I'm doing wrong..

Thanks

**Comment by lyrixx** [comment]
This is really strange indeed. Maybe you have ACL or something like that?
Do it work with the RAW API?

**Comment by scortellino** [comment]
> This is really strange indeed. Maybe you have ACL or something like that?
> Do it work with the RAW API?

Hm yeah the RAW API (via terminal and PHP Curl) does return the value. Maybe Guzzle is the issue. I'll dig further. Thanks

**Comment by lyrixx** [comment]
We moved to symfony/http-client. 
So I'm closing this issue.

Feel free to re-open is the bug it still here
