### ISSUE TITLE
Status 4xx is considered an exception

### ISSUE THREAD

**Issue by FabianTe** [FriendsOfPHP/consul-php-sdk#46]
Hi,

when trying to access KV values that do not exist, Consul responds with a status 404 which is fine. I have the `http_errors` option on the Guzzle client set to false but I still get exceptions that this library creates.

**Comment by lyrixx** [comment]
Hello,

IMHO, this is find to get an Exception on a `get()` (and not a `find()`) method when something does not exist.

That's why I'm closing this issue.

Thanks for reporting it.
