### ISSUE TITLE
Guzzle v7 Support

### ISSUE THREAD

**Issue by mpash** [FriendsOfPHP/consul-php-sdk#49]
Please help upstream packages using [Laravel v8](https://laravel.com/docs/8.x/upgrade) by targeting v7 Guzzle.

![image](https://user-images.githubusercontent.com/48454220/98047407-71e3a400-1df1-11eb-9b36-d51fdb900f15.png)

**Comment by lyrixx** [comment]
I would switch to symfony/http-client instead.

Would you mind submitting a PR?

**Comment by mpash** [comment]
I'd be happy to @lyrixx

**Comment by mpash** [comment]
@lyrixx can you please review the PR that has been sitting here. I don't like things lingering.

**Comment by lyrixx** [comment]
Oh, sorry I missed it :)
