### ISSUE TITLE
Support symfony/http-client 6.0

### ISSUE THREAD

**Issue by jlekowski** [FriendsOfPHP/consul-php-sdk#57]
The change itself is pretty straightforward: set Symfony HTTP Client constraints to `symfony/http-client": "^5.1|^6.0"`.

Not sure how about updating the docs as it's currently:
| SDK Version | Guzzle Version | Symfony HTTP Client |
| ----------- | -------------- | ------------------- |
| 1.x         | >=4, <6        | N/A                 |
| 2.x         | 6              | N/A                 |
| 3.x         | 6              | N/A                 |
| 4.x         | N/A            | 5                   |

and would need to become something like (assuming you decide not to bump the version to 5.0):
| SDK Version | Guzzle Version | Symfony HTTP Client |
| ----------- | -------------- | ------------------- |
| 1.x         | >=4, <6        | N/A                 |
| 2.x         | 6              | N/A                 |
| 3.x         | 6              | N/A                 |
| 4.x         | N/A            | 5                   |
| >=4.2       | N/A            | 5 or 6               |

@lyrixx, I can create a PR if you want, I'm only not sure what your preferred way to update the docs is, thanks.

**Comment by lyrixx** [comment]
Hello, You proposal with the latest table seems good to me.

**Comment by jlekowski** [comment]
@lyrixx. pls have a look at the PR https://github.com/FriendsOfPHP/consul-php-sdk/pull/58
