### ISSUE TITLE
Support symfony/http-client 7.0

### ISSUE THREAD

**Issue by kochen** [FriendsOfPHP/consul-php-sdk#62]
Symfony 7.0.0 is out!

**Comment by kochen** [comment]
@lyrixx could this be released please?

**Comment by lyrixx** [comment]
yes, sorry for the delay, I'm sick... https://github.com/FriendsOfPHP/consul-php-sdk/releases/tag/v5.1.0

**Comment by kochen** [comment]
Thank you!

get better soon!
